import '../models/product_model.dart';

class ProductRepository {
  final List<Product> _products = [
    // Frutas
    Product(
      id: '1',
      name: 'Maçã',
      description: 'Maçãs vermelhas e suculentas',
      price: 1.5,
      imageUrl: 'assets/images/maca.png',
      category: 'Frutas',
    ),
    Product(
      id: '2',
      name: 'Banana',
      description: 'Bananas maduras',
      price: 1.0,
      imageUrl: 'assets/images/banana.webp',
      category: 'Frutas',
    ),
    Product(
      id: '3',
      name: 'Laranja',
      description: 'Laranjas frescas',
      price: 2.0,
      imageUrl: 'assets/images/laranja.webp',
      category: 'Frutas',
    ),
    Product(
      id: '4',
      name: 'Uva',
      description: 'Uvas doces e frescas',
      price: 3.0,
      imageUrl: 'assets/images/uva.png',
      category: 'Frutas',
    ),
    Product(
      id: '5',
      name: 'Pêra',
      description: 'Pêras suculentas e doces',
      price: 2.5,
      imageUrl: 'assets/images/pera.png',
      category: 'Frutas',
    ),
    // Legumes
    Product(
      id: '6',
      name: 'Tomate',
      description: 'Tomates frescos e vermelhos',
      price: 1.2,
      imageUrl: 'assets/images/tomate.png',
      category: 'Legumes',
    ),
    Product(
      id: '7',
      name: 'Cenoura',
      description: 'Cenouras crocantes e frescas',
      price: 0.8,
      imageUrl: 'assets/images/cenoura.png',
      category: 'Legumes',
    ),
    Product(
      id: '8',
      name: 'Batata',
      description: 'Batatas grandes e saudáveis',
      price: 1.0,
      imageUrl: 'assets/images/batata.png',
      category: 'Legumes',
    ),
    Product(
      id: '9',
      name: 'Brócolis',
      description: 'Brócolis frescos e verdes',
      price: 2.0,
      imageUrl: 'assets/images/brocolis.png',
      category: 'Legumes',
    ),
    Product(
      id: '10',
      name: 'Alface',
      description: 'Alface crocante e verde',
      price: 0.5,
      imageUrl: 'assets/images/alface.png',
      category: 'Legumes',
    ),
    // Bebidas
    Product(
      id: '11',
      name: 'Suco de Laranja',
      description: 'Suco de laranja fresco',
      price: 3.0,
      imageUrl: 'assets/images/suco_laranja.png',
      category: 'Bebidas',
    ),
    Product(
      id: '12',
      name: 'Refrigerante',
      description: 'Refrigerante gelado',
      price: 2.0,
      imageUrl: 'assets/images/refri.png',
      category: 'Bebidas',
    ),
    Product(
      id: '13',
      name: 'Água',
      description: 'Água mineral',
      price: 1.0,
      imageUrl: 'assets/images/agua_mineral.png',
      category: 'Bebidas',
    ),
    Product(
      id: '14',
      name: 'Cerveja',
      description: 'Cerveja gelada',
      price: 4.0,
      imageUrl: 'assets/images/cerveja.png',
      category: 'Bebidas',
    ),
    Product(
      id: '15',
      name: 'Vinho',
      description: 'Vinho tinto',
      price: 15.0,
      imageUrl: 'assets/images/vinho.png',
      category: 'Bebidas',
    ),
    // Lanches
    Product(
      id: '16',
      name: 'Sanduíche',
      description: 'Sanduíche natural',
      price: 5.0,
      imageUrl: 'assets/images/sanduiche.png',
      category: 'Lanches',
    ),
    Product(
      id: '17',
      name: 'Bolo',
      description: 'Bolo de chocolate',
      price: 3.5,
      imageUrl: 'assets/images/bolo.png',
      category: 'Lanches',
    ),
    Product(
      id: '18',
      name: 'Salgadinho',
      description: 'Salgadinhos variados',
      price: 2.0,
      imageUrl: 'assets/images/salgadinho.png',
      category: 'Lanches',
    ),
    Product(
      id: '19',
      name: 'Biscoito',
      description: 'Biscoitos doces',
      price: 1.5,
      imageUrl: 'assets/images/biscoito.png',
      category: 'Lanches',
    ),
    Product(
      id: '20',
      name: 'Pizza',
      description: 'Fatias de pizza',
      price: 4.0,
      imageUrl: 'assets/images/pizza.png',
      category: 'Lanches',
    ),
    // Produtos Higiênicos
    Product(
      id: '21',
      name: 'Sabonete',
      description: 'Sabonete hidratante',
      price: 1.0,
      imageUrl: 'assets/images/sabonete.png',
      category: 'Produtos Higiênicos',
    ),
    Product(
      id: '22',
      name: 'Shampoo',
      description: 'Shampoo revitalizante',
      price: 7.0,
      imageUrl: 'assets/images/shampoo.png',
      category: 'Produtos Higiênicos',
    ),
    Product(
      id: '23',
      name: 'Condicionador',
      description: 'Condicionador nutritivo',
      price: 7.0,
      imageUrl: 'assets/images/condicionador.png',
      category: 'Produtos Higiênicos',
    ),
    Product(
      id: '24',
      name: 'Pasta de Dente',
      description: 'Pasta de dente refrescante',
      price: 3.0,
      imageUrl: 'assets/images/pasta.png',
      category: 'Produtos Higiênicos',
    ),
    Product(
      id: '25',
      name: 'Desodorante',
      description: 'Desodorante antitranspirante',
      price: 5.0,
      imageUrl: 'assets/images/desodorante.png',
      category: 'Produtos Higiênicos',
    ),
    // Cereais
    Product(
      id: '26',
      name: 'Aveia',
      description: 'Aveia integral',
      price: 2.0,
      imageUrl: 'assets/images/aveia.png',
      category: 'Cereais',
    ),
    Product(
      id: '27',
      name: 'Granola',
      description: 'Granola crocante',
      price: 3.0,
      imageUrl: 'assets/images/granola.png',
      category: 'Cereais',
    ),
    Product(
      id: '28',
      name: 'Flocos de Milho',
      description: 'Flocos de milho',
      price: 1.5,
      imageUrl: 'assets/images/floco_milho.png',
      category: 'Cereais',
    ),
    Product(
      id: '29',
      name: 'Trigo',
      description: 'Trigo para quibe',
      price: 2.0,
      imageUrl: 'assets/images/trigo.png',
      category: 'Cereais',
    ),
    Product(
      id: '30',
      name: 'Cevada',
      description: 'Cevada em grãos',
      price: 2.5,
      imageUrl: 'assets/images/cevada.png',
      category: 'Cereais',
    ),
  ];

  Future<List<Product>> fetchProducts() async {
    await Future.delayed(const Duration(seconds: 2));
    return _products;
  }
}
